<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Grupo_model');
    } 

    /*
     * Listing of grupo
     */
    function index()
    {
        $data['grupo'] = $this->Grupo_model->get_all_grupo();
        
        $data['_view'] = 'grupo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new grupo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'grupo_nombre' => $this->input->post('grupo_nombre'),
				'grupo_descripcion' => $this->input->post('grupo_descripcion'),
            );
            
            $grupo_id = $this->Grupo_model->add_grupo($params);
            redirect('grupo/index');
        }
        else
        {            
            $data['_view'] = 'grupo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a grupo
     */
    function edit($grupo_id)
    {   
        // check if the grupo exists before trying to edit it
        $data['grupo'] = $this->Grupo_model->get_grupo($grupo_id);
        
        if(isset($data['grupo']['grupo_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'grupo_nombre' => $this->input->post('grupo_nombre'),
					'grupo_descripcion' => $this->input->post('grupo_descripcion'),
                );

                $this->Grupo_model->update_grupo($grupo_id,$params);            
                redirect('grupo/index');
            }
            else
            {
                $data['_view'] = 'grupo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The grupo you are trying to edit does not exist.');
    } 

    /*
     * Deleting grupo
     */
    function remove($grupo_id)
    {
        $grupo = $this->Grupo_model->get_grupo($grupo_id);

        // check if the grupo exists before trying to delete it
        if(isset($grupo['grupo_id']))
        {
            $this->Grupo_model->delete_grupo($grupo_id);
            redirect('grupo/index');
        }
        else
            show_error('The grupo you are trying to delete does not exist.');
    }
    
}
