<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarea_estudiante extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tarea_estudiante_model');
    } 

    /*
     * Listing of tarea_estudiante
     */
    function index()
    {
        $data['tarea_estudiante'] = $this->Tarea_estudiante_model->get_all_tarea_estudiante();
        
        $data['_view'] = 'tarea_estudiante/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tarea_estudiante
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tarea_id' => $this->input->post('tarea_id'),
				'tareaes_titulo' => $this->input->post('tareaes_titulo'),
				'tareaes_archivo' => $this->input->post('tareaes_archivo'),
				'tareaes_fechahora' => $this->input->post('tareaes_fechahora'),
				'tareaes_descripcion' => $this->input->post('tareaes_descripcion'),
            );
            
            $tarea_estudiante_id = $this->Tarea_estudiante_model->add_tarea_estudiante($params);
            redirect('tarea_estudiante/index');
        }
        else
        {            
            $data['_view'] = 'tarea_estudiante/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tarea_estudiante
     */
    function edit($tareaes_id)
    {   
        // check if the tarea_estudiante exists before trying to edit it
        $data['tarea_estudiante'] = $this->Tarea_estudiante_model->get_tarea_estudiante($tareaes_id);
        
        if(isset($data['tarea_estudiante']['tareaes_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tarea_id' => $this->input->post('tarea_id'),
					'tareaes_titulo' => $this->input->post('tareaes_titulo'),
					'tareaes_archivo' => $this->input->post('tareaes_archivo'),
					'tareaes_fechahora' => $this->input->post('tareaes_fechahora'),
					'tareaes_descripcion' => $this->input->post('tareaes_descripcion'),
                );

                $this->Tarea_estudiante_model->update_tarea_estudiante($tareaes_id,$params);            
                redirect('tarea_estudiante/index');
            }
            else
            {
                $data['_view'] = 'tarea_estudiante/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tarea_estudiante you are trying to edit does not exist.');
    } 

    /*
     * Deleting tarea_estudiante
     */
    function remove($tareaes_id)
    {
        $tarea_estudiante = $this->Tarea_estudiante_model->get_tarea_estudiante($tareaes_id);

        // check if the tarea_estudiante exists before trying to delete it
        if(isset($tarea_estudiante['tareaes_id']))
        {
            $this->Tarea_estudiante_model->delete_tarea_estudiante($tareaes_id);
            redirect('tarea_estudiante/index');
        }
        else
            show_error('The tarea_estudiante you are trying to delete does not exist.');
    }
    
}
