<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarea extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tarea_model');
    } 

    /*
     * Listing of tarea
     */
    function index()
    {
        $data['tarea'] = $this->Tarea_model->get_all_tarea();
        
        $data['_view'] = 'tarea/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tarea
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'grupo_id' => $this->input->post('grupo_id'),
				'tarea_titulo' => $this->input->post('tarea_titulo'),
				'tarea_archivo' => $this->input->post('tarea_archivo'),
				'tarea_fecha' => $this->input->post('tarea_fecha'),
				'tarea_hora' => $this->input->post('tarea_hora'),
				'tarea_fechaentrega' => $this->input->post('tarea_fechaentrega'),
				'tarea_fechahora' => $this->input->post('tarea_fechahora'),
				'tarea_descripcion' => $this->input->post('tarea_descripcion'),
            );
            
            $tarea_id = $this->Tarea_model->add_tarea($params);
            redirect('tarea/index');
        }
        else
        {
			$this->load->model('Grupo_model');
			$data['all_grupo'] = $this->Grupo_model->get_all_grupo();
            
            $data['_view'] = 'tarea/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tarea
     */
    function edit($tarea_id)
    {   
        // check if the tarea exists before trying to edit it
        $data['tarea'] = $this->Tarea_model->get_tarea($tarea_id);
        
        if(isset($data['tarea']['tarea_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'grupo_id' => $this->input->post('grupo_id'),
					'tarea_titulo' => $this->input->post('tarea_titulo'),
					'tarea_archivo' => $this->input->post('tarea_archivo'),
					'tarea_fecha' => $this->input->post('tarea_fecha'),
					'tarea_hora' => $this->input->post('tarea_hora'),
					'tarea_fechaentrega' => $this->input->post('tarea_fechaentrega'),
					'tarea_fechahora' => $this->input->post('tarea_fechahora'),
					'tarea_descripcion' => $this->input->post('tarea_descripcion'),
                );

                $this->Tarea_model->update_tarea($tarea_id,$params);            
                redirect('tarea/index');
            }
            else
            {
				$this->load->model('Grupo_model');
				$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

                $data['_view'] = 'tarea/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tarea you are trying to edit does not exist.');
    } 

    /*
     * Deleting tarea
     */
    function remove($tarea_id)
    {
        $tarea = $this->Tarea_model->get_tarea($tarea_id);

        // check if the tarea exists before trying to delete it
        if(isset($tarea['tarea_id']))
        {
            $this->Tarea_model->delete_tarea($tarea_id);
            redirect('tarea/index');
        }
        else
            show_error('The tarea you are trying to delete does not exist.');
    }
    
}
