<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Video extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Video_model');
        $this->load->model('Grupo_model');
    } 

    /*
     * Listing of video
     */
    function index()
    {
        $data['video'] = $this->Video_model->get_all_video();
        
        $data['_view'] = 'video/index';
        $this->load->view('layouts/main',$data);
    }

    function grupo($grupo_id)
    {
        $data['video'] = $this->Video_model->get_video_grupo($grupo_id);
        $data['grupo_id'] = $grupo_id;
        $data['grupo'] = $this->Grupo_model->get_grupo($grupo_id);
        $data['_view'] = 'video/index';
        $this->load->view('layouts/main',$data);
    }
    /*
     * Adding a new video
     */
    function add($grupo_id)
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'grupo_id' => $grupo_id,
				'video_titulo' => $this->input->post('video_titulo'),
				'video_fecha' => $this->input->post('video_fecha'),
				'video_hora' => $this->input->post('video_hora'),
				'video_link' => $this->input->post('video_link'),
            );
            
            $video_id = $this->Video_model->add_video($params);
            redirect('video/grupo/'.$grupo_id);
        }
        else
        {
			$this->load->model('Grupo_model');
			$data['all_grupo'] = $this->Grupo_model->get_all_grupo();
            $data['grupo_id'] = $grupo_id;
            $data['grupo'] = $this->Grupo_model->get_grupo($grupo_id);
            $data['_view'] = 'video/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a video
     */
    function edit($video_id)
    {   
        // check if the video exists before trying to edit it
        $data['video'] = $this->Video_model->get_video($video_id);
        
        if(isset($data['video']['video_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'grupo_id' => $this->input->post('grupo_id'),
					'video_titulo' => $this->input->post('video_titulo'),
					'video_fecha' => $this->input->post('video_fecha'),
					'video_hora' => $this->input->post('video_hora'),
					'video_link' => $this->input->post('video_link'),
                );

                $this->Video_model->update_video($video_id,$params);            
                redirect('video/grupo/'.$this->input->post('grupo_id'));
            }
            else
            {
				$this->load->model('Grupo_model');
				$data['all_grupo'] = $this->Grupo_model->get_all_grupo();

                $data['_view'] = 'video/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The video you are trying to edit does not exist.');
    } 

    /*
     * Deleting video
     */
    function remove($video_id)
    {
        $video = $this->Video_model->get_video($video_id);

        // check if the video exists before trying to delete it
        if(isset($video['video_id']))
        {
            $this->Video_model->delete_video($video_id);
            redirect('video/index');
        }
        else
            show_error('The video you are trying to delete does not exist.');
    }
    
}
