<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by estudiante_id
     */
    function get_estudiante($estudiante_id)
    {
        return $this->db->get_where('estudiante',array('estudiante_id'=>$estudiante_id))->row_array();
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante()
    {
   
        $sql = $this->db->query("SELECT e.*, g.*
                                FROM estudiante e, grupo g 
                                
                                WHERE e.grupo_id=g.grupo_id

                                ORDER BY estudiante_id DESC LIMIT 50
                               
                                ")->result_array();
        return $sql;

    
    }

    function get_estudiante_grupo($grupo_id)
    {
   
        $sql = $this->db->query("SELECT e.*, g.*
                                FROM estudiante e, grupo g 
                                
                                WHERE e.grupo_id=g.grupo_id
                                and e.grupo_id=".$grupo_id." 

                                ORDER BY estudiante_id ASC 
                               
                                ")->result_array();
        return $sql;

    
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($estudiante_id,$params)
    {
        $this->db->where('estudiante_id',$estudiante_id);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($estudiante_id)
    {
        return $this->db->delete('estudiante',array('estudiante_id'=>$estudiante_id));
    }
}
