<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarea_estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tarea_estudiante by tareaes_id
     */
    function get_tarea_estudiante($tareaes_id)
    {
        return $this->db->get_where('tarea_estudiante',array('tareaes_id'=>$tareaes_id))->row_array();
    }
        
    /*
     * Get all tarea_estudiante
     */
    function get_all_tarea_estudiante()
    {
        $this->db->order_by('tareaes_id', 'desc');
        return $this->db->get('tarea_estudiante')->result_array();
    }
        
    /*
     * function to add new tarea_estudiante
     */
    function add_tarea_estudiante($params)
    {
        $this->db->insert('tarea_estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tarea_estudiante
     */
    function update_tarea_estudiante($tareaes_id,$params)
    {
        $this->db->where('tareaes_id',$tareaes_id);
        return $this->db->update('tarea_estudiante',$params);
    }
    
    /*
     * function to delete tarea_estudiante
     */
    function delete_tarea_estudiante($tareaes_id)
    {
        return $this->db->delete('tarea_estudiante',array('tareaes_id'=>$tareaes_id));
    }
}
