<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Video_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get video by video_id
     */
    function get_video($video_id)
    {
        return $this->db->get_where('video',array('video_id'=>$video_id))->row_array();
    }
        
    /*
     * Get all video
     */
    function get_all_video()
    {
        $this->db->order_by('video_id', 'desc');
        return $this->db->get('video')->result_array();
    }

    function get_video_grupo($grupo_id)
    {
   
        $sql = $this->db->query("SELECT e.*, g.*
                                FROM video e, grupo g 
                                
                                WHERE e.grupo_id=g.grupo_id
                                and e.grupo_id=".$grupo_id." 

                                ORDER BY video_id ASC 
                               
                                ")->result_array();
        return $sql;

    
    }
        
    /*
     * function to add new video
     */
    function add_video($params)
    {
        $this->db->insert('video',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update video
     */
    function update_video($video_id,$params)
    {
        $this->db->where('video_id',$video_id);
        return $this->db->update('video',$params);
    }
    
    /*
     * function to delete video
     */
    function delete_video($video_id)
    {
        return $this->db->delete('video',array('video_id'=>$video_id));
    }
}
